# Generated by Django 4.2.30 on 2026-05-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1有效 0删除)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='模型名称')),
                ('language', models.CharField(choices=[('zh', '中'), ('en', '英'), ('es', '西'), ('ja', '日'), ('ko', '韩'), ('ru', '俄'), ('fr', '法'), ('de', '德'), ('th', '泰'), ('it', '意'), ('ar', '阿')], default='zh', max_length=10, verbose_name='语种')),
                ('version', models.CharField(max_length=30, verbose_name='模型版本')),
                ('size', models.CharField(choices=[('base', 'base'), ('small', 'small'), ('large', 'large')], default='base', max_length=10, verbose_name='尺寸')),
                ('dir_path', models.CharField(blank=True, default='', max_length=500, verbose_name='模型文件夹路径')),
            ],
            options={
                'verbose_name': 'ASR模型',
                'db_table': 'asr_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1有效 0删除)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='音频名称')),
                ('language', models.CharField(choices=[('zh', '中'), ('en', '英'), ('es', '西'), ('ja', '日'), ('ko', '韩'), ('ru', '俄'), ('fr', '法'), ('de', '德'), ('th', '泰'), ('it', '意'), ('ar', '阿')], default='zh', max_length=10, verbose_name='语种')),
                ('audio_path', models.CharField(max_length=500, verbose_name='音频路径(URL)')),
                ('source', models.CharField(choices=[('Sota1', 'Sota1'), ('Sota2', 'Sota2'), ('Sota3', 'Sota3'), ('gf', 'gf'), ('outside', 'outside'), ('cv15', 'cv15'), ('30min', '30min')], default='outside', max_length=20, verbose_name='音频来源')),
                ('noise', models.CharField(choices=[('quiet', '安静'), ('low_mid', '中低'), ('mid_high', '中高'), ('high', '高噪')], default='quiet', max_length=20, verbose_name='噪声')),
                ('industry', models.CharField(choices=[('unknown', '未知'), ('economy', '经济'), ('finance', '金融'), ('medical', '医疗'), ('travel', '旅游'), ('food', '美食'), ('technology', '科技')], default='unknown', max_length=20, verbose_name='行业')),
                ('duration', models.FloatField(default=0, verbose_name='时长(秒)')),
                ('ref_text', models.TextField(blank=True, default='', verbose_name='参考文本')),
            ],
            options={
                'verbose_name': '音频',
                'db_table': 'audio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1有效 0删除)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='数据集名称')),
                ('language', models.CharField(choices=[('zh', '中'), ('en', '英'), ('es', '西'), ('ja', '日'), ('ko', '韩'), ('ru', '俄'), ('fr', '法'), ('de', '德'), ('th', '泰'), ('it', '意'), ('ar', '阿')], default='zh', max_length=10, verbose_name='语种')),
            ],
            options={
                'verbose_name': '数据集',
                'db_table': 'dataset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1有效 0删除)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='任务名称')),
                ('task_status', models.SmallIntegerField(choices=[(1, '进行中'), (2, '运行完成'), (3, '失败')], default=1, verbose_name='任务状态')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='asr.asrmodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '测试任务',
                'db_table': 'test_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='asr.audio')),
                ('dataset', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='asr.dataset')),
            ],
            options={
                'verbose_name': '数据集音频关联',
                'db_table': 'dataset_audio',
                'unique_together': {('dataset', 'audio')},
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='datasets',
            field=models.ManyToManyField(related_name='audios', through='asr.DatasetAudio', to='asr.dataset'),
        ),
        migrations.CreateModel(
            name='AsrModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='asr.asrmodel', verbose_name='模型')),
            ],
            options={
                'verbose_name': 'ASR模型文件',
                'db_table': 'asr_model_file',
            },
        ),
        migrations.CreateModel(
            name='TestTaskDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_audio', models.IntegerField(default=0, verbose_name='音频总数')),
                ('total_duration', models.FloatField(default=0, verbose_name='音频总时长(秒)')),
                ('avg_wer', models.FloatField(default=0, verbose_name='平均WER')),
                ('ret', models.FloatField(default=0, verbose_name='RET')),
                ('s_cnt', models.IntegerField(default=0, verbose_name='替换错误数')),
                ('i_cnt', models.IntegerField(default=0, verbose_name='多识别数')),
                ('d_cnt', models.IntegerField(default=0, verbose_name='漏识别数')),
                ('hit_cnt', models.IntegerField(default=0, verbose_name='命中数')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asr.dataset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_datasets', to='asr.testtask')),
            ],
            options={
                'verbose_name': '任务数据集统计',
                'db_table': 'test_task_dataset',
                'unique_together': {('task', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='TestAudioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_text', models.TextField(blank=True, default='', verbose_name='参考文本快照')),
                ('hyp_text', models.TextField(blank=True, default='', verbose_name='模型预测文本')),
                ('wer', models.FloatField(default=0, verbose_name='WER')),
                ('errors_json', models.JSONField(default=dict, verbose_name='错误细节(S/I/D等)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asr.audio')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asr.dataset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_results', to='asr.testtask')),
            ],
            options={
                'verbose_name': '音频识别结果',
                'db_table': 'test_audio_result',
                'unique_together': {('task', 'dataset', 'audio')},
            },
        ),
    ]
